### PR TITLE
Switch to new API platform

### PR DESCRIPTION
**Pull request by slokhorst**
**This is a breaking change.**
The DivideBV\Postnl\Postnl constructor no longer accepts a username
and password, but a single API key.

Please test all services, as I don't have access to everything.

For more information, see #55 and https://developer.postnl.nl/apis/new-api-platform

As this is a breaking change, it might be a good time to incorporate #32

### CODE REVIEW

**Comment by slokhorst** [comment]
People moving from the old platform to the new, need to request an API key at https://developer.postnl.nl/content/request-api-key

**Comment by ameenross** [comment]
So until they provide proper information on upgrading, I'm not going to take action here. I cannot justify the hours needed to sort everything out without an upgrade guide (unless we get budget from one of my company's clients for it).

I'm worried for example that not all services work with the new authentication method without upgrading to a newer version.

The only thing I can do without an upgrade guide is facilitate. If the community can test whether this works with every CIF service currently supported, then we can proceed.

**Comment by slokhorst** [comment]
FYI: I just got an email from PostNL that they will shut down the old endpoint on 1 November 2018.

screenshot_2018-06-28 wij zijn postnl en we hebben iets voor je postnl

**Comment by ameenross** [comment]
Good timing. I have an upcoming meeting with a customer where this can be discussed. Do they now have an upgrade guide?

**Comment by slokhorst** [comment]
They have this [Migration guide](https://developer.postnl.nl/browse-apis/delivery-options/migration-guide/).

**Comment by ameenross** [comment]
It links to a PDF, but the link doesn't even work.

**Comment by slokhorst** [comment]
Works for me: 
[step-by-step-guide-API-platform_tcm85-123489.pdf](https://github.com/DivideBV/Postnl/files/2148900/step-by-step-guide-API-platform_tcm85-123489.pdf)

**Comment by annuh** [comment]
It's only 3 months until 1 November 😀 
Can we help testing this?

**Comment by slokhorst** [comment]
You can test it out by adding this to your `composer.json`:

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/slokhorst/Postnl"
    }
]
```

change the line in `"require"` to `"dividebv/postnl": "dev-new_api_platform"` and run `composer update`.

Now request an API key at https://developer.postnl.nl/request-api-key/ and use that in your `new Postnl(...)` call (see [updated readme](https://github.com/slokhorst/Postnl/blob/37b04e89d132349e99aaaa4f9a3282917a008a40/README.md#example)).

**Comment by ameenross** [comment]
I'm working on getting some time for this from the client. The PR looked good at first glance, but of course I need a bit more time to properly verify it. I hope to get this time soon

**Comment by ameenross** [comment]
I'm worried about this statement on the page to request an API key.

> Dependent on which APIs you would like to use, you need separate keys for each API

Otherwise, I'm working on getting this merged today. But I won't release a stable 2.0 yet until we know what's going on with the multiple API key thing.

**Comment by slokhorst** [comment]
I think that's incorrect. I have a single key for multiple APIs:

image

Edit: maybe you need a separate key for the paid APIs (IBANcheck, Kredietcheck, etc)?

**Comment by ameenross** [comment]
We'll need to figure out the details I guess... It would be no fun if `Postnl::__construct` needs to request an array of api keys.

**Comment by ameenross** [comment]
2.0.0-beta1 released

**Pull request merged**
