### PR TITLE
Allow Printertype of label to be specified on generateLabel()

### PR DESCRIPTION
**Pull request by wvdongen**
Little adjustment so the type that fits best with your local printing situation can be specified.

### CODE REVIEW

**Comment by ameenross** [comment]
Thanks for the contribution. I'd prefer the variable to be camel cased: `$printerType`. Otherwise it's good and I intend on merging it.

The reason some variables are cased differently is because they are serialized by the SOAP stack, so the casing needs to (or should) comply with the CIF spec.

**Comment by wvdongen** [comment]
I agree that $printerType is the way it should be written. However, in this case I think it is better to use constant naming of variables throughout the code, so I think we should go for $Printertype :)

**Comment by slokhorst** [comment]
I wouldn't call `$shipment`, `$confirm`, `$Printertype` constant naming to be honest. :)

**Comment by wvdongen** [comment]
Alright people, 2 votes against 1 :) Still think `$Printertype` is better as it is named this way in the rest of the code. I've changed it, please merge.

**Comment by ameenross** [comment]
Looks good. Merging. I'm also going to add the parameter to `generateLabelWithoutConfirm`.

**Comment by ameenross** [comment]
Please note that I also switched the order of the parameters, as `$confirm` is there for internal use. It aught not be used by a consumer of the library. Released new version `0.9.0`

**Pull request merged**
